version: "3"

services:

  postgres:
    image: "postgres" # use latest official postgres version
    env_file:
      - postgres/database.env # configure postgres
    volumes:
      - postgres:/data/postgres # persist data even if container shuts downvolumes:
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  adminer:
    image: "adminer"
    ports:
      - "8090:8080"
    networks:
      - postgres
    restart: on-failure
    
  backend-api:
    container_name: backend-api
    build: backend-api
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
